# Generated by Django 6.0.4 on 2026-04-12 01:35

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Credential',
            fields=[
                ('credential_id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('aft_number', models.IntegerField()),
                ('email', models.EmailField(max_length=255, unique=True)),
                ('password', models.CharField(max_length=255)),
                ('googleHash', models.CharField(max_length=255)),
                ('is_staff', models.BooleanField(default=False)),
                ('active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'credential',
                'verbose_name_plural': 'credentials',
                'db_table': 'credential',
                'constraints': [models.UniqueConstraint(fields=('email',), name='credential_unique_email'), models.UniqueConstraint(fields=('aft_number',), name='credential_unique_aft_number'), models.CheckConstraint(condition=models.Q(('aft_number__gte', 1000000), ('aft_number__lte', 9999999)), name='credential_aft_number_valid')],
            },
        ),
        migrations.CreateModel(
            name='Token',
            fields=[
                ('token_id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('token', models.CharField(max_length=255)),
                ('refresh_token', models.CharField(max_length=255)),
                ('credential', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='tcr_auth.credential')),
            ],
        ),
    ]
