# Generated by Django 6.0.3 on 2026-04-06 16:15

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Address',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('street', models.CharField(max_length=50)),
                ('number', models.CharField(max_length=30)),
                ('city', models.CharField(max_length=50)),
                ('state', models.CharField(max_length=50)),
                ('zipCode', models.CharField(max_length=30)),
                ('country', models.CharField(max_length=50)),
            ],
            options={
                'db_table': 'address',
            },
        ),
        migrations.CreateModel(
            name='Member',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('aftNumber', models.IntegerField()),
                ('firstname', models.CharField(max_length=50)),
                ('lastname', models.CharField(max_length=50)),
                ('gender', models.CharField(max_length=1)),
                ('birth_date', models.DateField()),
                ('phone_number', models.CharField(max_length=20)),
                ('email', models.EmailField(max_length=254)),
                ('password', models.CharField(max_length=50)),
                ('annualFeePaid', models.BooleanField(default=False)),
                ('address', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='residents', to='tcr_backend.address')),
            ],
            options={
                'db_table': 'member',
                'ordering': ['-lastname', '-firstname'],
            },
        ),
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=50)),
                ('description', models.TextField()),
                ('ageMin', models.IntegerField()),
                ('ageMax', models.IntegerField()),
                ('birthYearMin', models.IntegerField()),
                ('birthYearMax', models.IntegerField()),
                ('gender', models.CharField(max_length=1)),
                ('parentCategory', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='subCategories', to='tcr_backend.category')),
            ],
            options={
                'db_table': 'category',
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='Court',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('number', models.IntegerField(default=1)),
                ('type', models.CharField(max_length=20)),
            ],
            options={
                'db_table': 'court',
                'ordering': ['number'],
            },
        ),
        migrations.CreateModel(
            name='CourtEvent',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('dateCreated', models.DateTimeField(auto_now_add=True)),
                ('dateModified', models.DateTimeField(auto_now=True)),
                ('dateReservation', models.DateField()),
                ('status', models.CharField(max_length=255)),
            ],
            options={
                'db_table': 'court_event',
                'ordering': ['-dateReservation'],
            },
        ),
        migrations.CreateModel(
            name='Rank',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=50)),
            ],
            options={
                'db_table': 'rank',
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='Administrator',
            fields=[
                ('member_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='tcr_backend.member')),
            ],
            options={
                'db_table': 'administrator',
            },
            bases=('tcr_backend.member',),
        ),
        migrations.AddField(
            model_name='member',
            name='categories',
            field=models.ManyToManyField(related_name='members', to='tcr_backend.category'),
        ),
        migrations.CreateModel(
            name='Event',
            fields=[
                ('courtevent_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='tcr_backend.courtevent')),
                ('description', models.CharField(max_length=255)),
                ('isAllDay', models.BooleanField(default=False)),
            ],
            options={
                'db_table': 'event',
                'ordering': ['-dateReservation'],
            },
            bases=('tcr_backend.courtevent',),
        ),
        migrations.CreateModel(
            name='Reservation',
            fields=[
                ('courtevent_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='tcr_backend.courtevent')),
                ('isDouble', models.BooleanField(default=False)),
            ],
            options={
                'db_table': 'reservation',
                'ordering': ['-dateReservation'],
            },
            bases=('tcr_backend.courtevent',),
        ),
        migrations.CreateModel(
            name='MemberRank',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('dateCreated', models.DateTimeField(auto_now_add=True)),
                ('points', models.FloatField()),
                ('member', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='memberRanks', to='tcr_backend.member')),
                ('rank', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='members', to='tcr_backend.rank')),
            ],
            options={
                'db_table': 'member_rank',
                'ordering': ['-dateCreated'],
            },
        ),
        migrations.CreateModel(
            name='Subscription',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('dateCreated', models.DateTimeField()),
                ('year', models.IntegerField()),
                ('fee', models.FloatField()),
                ('paidInCash', models.BooleanField()),
                ('reference', models.CharField(max_length=50)),
                ('member', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='subscriptions', to='tcr_backend.member')),
            ],
            options={
                'db_table': 'subscription',
                'ordering': ['-dateCreated'],
            },
        ),
        migrations.CreateModel(
            name='TimeSlot',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('dateCreated', models.DateTimeField()),
                ('date', models.DateField()),
                ('startTime', models.TimeField()),
                ('endTime', models.TimeField()),
                ('status', models.TextField()),
                ('court', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='timeSlots', to='tcr_backend.court')),
                ('courtEvent', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='timeSlots', to='tcr_backend.courtevent')),
            ],
            options={
                'db_table': 'time_slot',
                'ordering': ['-date', 'startTime', 'endTime'],
            },
        ),
        migrations.AddConstraint(
            model_name='member',
            constraint=models.UniqueConstraint(fields=('email',), name='unique_email'),
        ),
        migrations.AddConstraint(
            model_name='member',
            constraint=models.UniqueConstraint(fields=('aftNumber',), name='unique_aft_number'),
        ),
        migrations.AddConstraint(
            model_name='category',
            constraint=models.UniqueConstraint(fields=('name',), name='unique_name'),
        ),
        migrations.AddField(
            model_name='event',
            name='author',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='events', to='tcr_backend.administrator'),
        ),
        migrations.AddField(
            model_name='reservation',
            name='author',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='ownedReservations', to='tcr_backend.member'),
        ),
        migrations.AddField(
            model_name='reservation',
            name='participants',
            field=models.ManyToManyField(related_name='participants', to='tcr_backend.member'),
        ),
    ]
