# Generated by Django 6.0.4 on 2026-04-21 08:57

import django.core.validators
import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('auth', '0012_alter_user_first_name_max_length'),
    ]

    operations = [
        migrations.CreateModel(
            name='Member',
            fields=[
                ('is_superuser', models.BooleanField(default=False, help_text='Designates that this user has all permissions without explicitly assigning them.', verbose_name='superuser status')),
                ('is_staff', models.BooleanField(default=False, help_text='Designates whether the user can log into this admin site.', verbose_name='staff status')),
                ('is_active', models.BooleanField(default=True, help_text='Designates whether this user should be treated as active. Unselect this instead of deleting accounts.', verbose_name='active')),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('aft_id', models.CharField(max_length=7, unique=True, validators=[django.core.validators.RegexValidator(code='invalid', message='Member aft ID must be between 1000000 and 9999999', regex='^[0-9]\\d{6}$')])),
                ('firstname', models.CharField(max_length=50)),
                ('lastname', models.CharField(max_length=50)),
                ('gender', models.CharField(max_length=1)),
                ('birthdate', models.DateField()),
                ('phone_number', models.CharField(max_length=20)),
                ('email', models.EmailField(max_length=254, unique=True)),
                ('password', models.CharField(max_length=255)),
                ('annual_fee_paid', models.BooleanField(default=False)),
                ('date_joined', models.DateTimeField(auto_now_add=True)),
                ('last_login', models.DateTimeField(blank=True, default=None, null=True)),
                ('groups', models.ManyToManyField(blank=True, help_text='The groups this user belongs to. A user will get all permissions granted to each of their groups.', related_name='user_set', related_query_name='user', to='auth.group', verbose_name='groups')),
                ('user_permissions', models.ManyToManyField(blank=True, help_text='Specific permissions for this user.', related_name='user_set', related_query_name='user', to='auth.permission', verbose_name='user permissions')),
            ],
            options={
                'db_table': 'member',
                'ordering': ['-lastname', '-firstname'],
            },
        ),
        migrations.CreateModel(
            name='Address',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('street', models.CharField(max_length=50)),
                ('number', models.CharField(max_length=30)),
                ('city', models.CharField(max_length=50)),
                ('state', models.CharField(max_length=50)),
                ('zip_code', models.CharField(max_length=30)),
                ('country', models.CharField(max_length=50)),
            ],
            options={
                'db_table': 'address',
            },
        ),
        migrations.CreateModel(
            name='Court',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('number', models.IntegerField(default=0)),
                ('type', models.CharField(max_length=50)),
            ],
            options={
                'db_table': 'court',
                'ordering': ['number'],
            },
        ),
        migrations.CreateModel(
            name='CourtEvent',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('date_created', models.DateTimeField(auto_now_add=True)),
                ('date_modified', models.DateTimeField(auto_now=True)),
                ('date_reservation', models.DateField()),
                ('status', models.CharField(max_length=255)),
                ('court', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='court_events', to='tcr_backend.court')),
            ],
            options={
                'db_table': 'court_event',
                'ordering': ['-date_reservation'],
            },
        ),
        migrations.CreateModel(
            name='Rank',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('order', models.IntegerField(default=0)),
                ('name', models.CharField(max_length=50)),
            ],
            options={
                'db_table': 'rank',
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='Admin',
            fields=[
                ('member_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'admin',
            },
            bases=('tcr_backend.member',),
        ),
        migrations.AddField(
            model_name='member',
            name='address',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='residents', to='tcr_backend.address'),
        ),
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=50)),
                ('description', models.TextField()),
                ('age_min', models.IntegerField(null=True)),
                ('age_max', models.IntegerField(null=True)),
                ('birth_year_min', models.IntegerField(null=True)),
                ('birth_year_max', models.IntegerField(null=True)),
                ('gender', models.CharField(max_length=1)),
                ('parentCategory', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='subCategories', to='tcr_backend.category')),
            ],
            options={
                'db_table': 'category',
                'ordering': ['name'],
            },
        ),
        migrations.AddField(
            model_name='member',
            name='categories',
            field=models.ManyToManyField(related_name='members', to='tcr_backend.category'),
        ),
        migrations.CreateModel(
            name='Event',
            fields=[
                ('courtevent_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='tcr_backend.courtevent')),
                ('description', models.TextField()),
                ('isAllDay', models.BooleanField(default=False)),
            ],
            options={
                'db_table': 'event',
                'ordering': ['-date_reservation'],
            },
            bases=('tcr_backend.courtevent',),
        ),
        migrations.CreateModel(
            name='Reservation',
            fields=[
                ('courtevent_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='tcr_backend.courtevent')),
                ('is_double', models.BooleanField(default=False)),
            ],
            options={
                'db_table': 'reservation',
                'ordering': ['-date_reservation'],
            },
            bases=('tcr_backend.courtevent',),
        ),
        migrations.AddField(
            model_name='courtevent',
            name='participants',
            field=models.ManyToManyField(related_name='participations', to=settings.AUTH_USER_MODEL),
        ),
        migrations.CreateModel(
            name='MemberRank',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('date_created', models.DateTimeField(auto_now_add=True)),
                ('points', models.FloatField()),
                ('member', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='memberRanks', to=settings.AUTH_USER_MODEL)),
                ('rank', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='members', to='tcr_backend.rank')),
            ],
            options={
                'db_table': 'member_rank',
                'ordering': ['-date_created'],
            },
        ),
        migrations.CreateModel(
            name='Subscription',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('date_created', models.DateTimeField()),
                ('year', models.IntegerField()),
                ('fee', models.FloatField()),
                ('paid_in_cash', models.BooleanField(default=False)),
                ('reference', models.CharField(max_length=50)),
                ('member', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='subscriptions', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'subscription',
                'ordering': ['-date_created'],
            },
        ),
        migrations.CreateModel(
            name='TimeSlot',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('date_created', models.DateTimeField()),
                ('date', models.DateField()),
                ('start_time', models.TimeField()),
                ('end_time', models.TimeField()),
                ('status', models.CharField(max_length=100)),
                ('court', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='time_slots', to='tcr_backend.court')),
            ],
            options={
                'db_table': 'time_slot',
                'ordering': ['-date', 'start_time', 'end_time'],
            },
        ),
        migrations.AddConstraint(
            model_name='category',
            constraint=models.UniqueConstraint(fields=('name',), name='unique_name'),
        ),
        migrations.AddConstraint(
            model_name='member',
            constraint=models.UniqueConstraint(fields=('email',), name='unique_email'),
        ),
        migrations.AddConstraint(
            model_name='member',
            constraint=models.UniqueConstraint(fields=('aft_id',), name='unique_aft_id'),
        ),
        migrations.AddField(
            model_name='event',
            name='author',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='events', to='tcr_backend.admin'),
        ),
        migrations.AddField(
            model_name='reservation',
            name='author',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='reservations', to=settings.AUTH_USER_MODEL),
        ),
    ]
