# Generated by Django 6.0.3 on 2026-04-06 16:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tcr_backend', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='category',
            name='ageMax',
            field=models.IntegerField(null=True),
        ),
        migrations.AlterField(
            model_name='category',
            name='ageMin',
            field=models.IntegerField(null=True),
        ),
        migrations.AlterField(
            model_name='category',
            name='birthYearMax',
            field=models.IntegerField(null=True),
        ),
        migrations.AlterField(
            model_name='category',
            name='birthYearMin',
            field=models.IntegerField(null=True),
        ),
    ]
