# Generated by Django 6.0.4 on 2026-05-15 06:06

import django.core.validators
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tcr_backend', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Plan',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('title', models.CharField(max_length=255)),
                ('subtitle', models.CharField(max_length=255)),
                ('summary', models.TextField()),
                ('description', models.TextField(blank=True, null=True)),
                ('price', models.DecimalField(decimal_places=2, max_digits=10)),
                ('currency', models.CharField(max_length=100)),
                ('currency_symbol', models.CharField(blank=True, max_length=30, null=True)),
            ],
            options={
                'db_table': 'plan',
            },
        ),
        migrations.AlterModelOptions(
            name='admin',
            options={'ordering': ['email']},
        ),
        migrations.AlterField(
            model_name='member',
            name='aft_id',
            field=models.CharField(max_length=7, unique=True, validators=[django.core.validators.RegexValidator(code='invalid', message='Member aft ID must be between 1000000 and 9999999', regex='^[0-9]\\d{6}$')], verbose_name='Identifiant AFT'),
        ),
    ]
