# Generated by Django 6.0.4 on 2026-05-15 07:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tcr_backend', '0002_plan_alter_admin_options_alter_member_aft_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='plan',
            name='img_url',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
