# Generated by Django 6.0.3 on 2026-04-06 16:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tcr_backend', '0002_alter_category_agemax_alter_category_agemin_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='rank',
            name='order',
            field=models.IntegerField(default=0),
        ),
    ]
