# Generated by Django 6.0.4 on 2026-05-15 07:13

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('tcr_backend', '0003_plan_img_url'),
    ]

    operations = [
        migrations.RenameField(
            model_name='plan',
            old_name='img_url',
            new_name='img_src',
        ),
    ]
