# Generated by Django 6.0.4 on 2026-05-15 09:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tcr_backend', '0004_rename_img_url_plan_img_src'),
    ]

    operations = [
        migrations.AddField(
            model_name='plan',
            name='price_id',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='plan',
            name='product_id',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
