# Generated by Django 6.0.4 on 2026-05-15 22:32

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tcr_backend', '0005_plan_price_id_plan_product_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='subscription',
            name='date_created',
            field=models.DateTimeField(auto_now_add=True),
        ),
        migrations.CreateModel(
            name='Payment',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('expired_at', models.DateTimeField(blank=True, null=True)),
                ('checkout_session_id', models.CharField(max_length=255)),
                ('amount_total', models.DecimalField(decimal_places=2, max_digits=10)),
                ('amount_subtotal', models.DecimalField(decimal_places=2, max_digits=10)),
                ('currency', models.CharField(max_length=5)),
                ('status', models.CharField(max_length=255)),
                ('payment_status', models.CharField(max_length=255)),
                ('url', models.URLField(max_length=255)),
                ('plan', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='payments', to='tcr_backend.plan')),
                ('subscription', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='payments', to='tcr_backend.subscription')),
            ],
            options={
                'db_table': 'payment',
                'ordering': ['-created_at'],
            },
        ),
    ]
