# Generated by Django 6.0.4 on 2026-05-17 06:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('tcr_backend', '0006_alter_subscription_date_created_payment'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='payment',
            name='url',
        ),
    ]
