# Generated by Django 6.0.4 on 2026-05-17 07:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tcr_backend', '0007_remove_payment_url'),
    ]

    operations = [
        migrations.AlterField(
            model_name='subscription',
            name='reference',
            field=models.CharField(max_length=255),
        ),
    ]
