# Generated by Django 6.0.4 on 2026-05-17 07:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tcr_backend', '0008_alter_subscription_reference'),
    ]

    operations = [
        migrations.AlterField(
            model_name='subscription',
            name='fee',
            field=models.DecimalField(decimal_places=2, max_digits=10),
        ),
    ]
