const ApiRoutes = {
  Home : '/dashboard',
  MemberLogin : '/auth/member/login',
  AdminLogin : '/auth/admin/login',
  AdminLoginGoogle: '/auth/admin/login/google',
  UpdatePassword : '/auth/change_password',
  RefreshToken : '/auth/refresh_token',
  Me : '/auth/whoami',
  Logout : '/auth/logout',
  CsrfToken : '/auth/csrf_token',
  ChangePassword : '/auth/change_password',
  UpdateProfile : '/api/members/',
  MemberList : '/api/members/',
  MemberRetrieve : '/api/members/',
  MemberDelete: '/api/members/',
  StripeCheckoutSession : '/api/payment/checkout_session',
  PlanList: '/api/plans',
  CourtList: '/api/courts',
  ListCategories : '/api/categories/',
  ListRanks : '/api/ranks/',
  ListReservations: '/api/reservations/',
  CreateReservation : '/api/reservations/',
  MyReservations: '/api/reservations/me/',
  DeleteReservation : '/api/reservations/',
  ListEvents : '/api/events/',
  CreateEvent : '/api/events/',
  ListCourts: '/api/courts/',
  CreateCourt: '/api/courts/',
  DeleteCourt: '/api/courts/',
} as const

export default ApiRoutes

